export const DR_ALPHA = "#f1eaff"; /* app lettering */
export const DR_ALPHA_RGB = "241, 234, 255";
export const DR_BETA = "#130e21"; /* app background */
export const DR_BETA_RGB = "19, 14, 33";
export const DR_GAMMA = "#231645"; /* app foreground contrast */
export const DR_GAMMA_RGB = "35, 22, 69";
export const DR_DELTA = "#5200ff";
export const DR_DELTA_RGB = "82, 0, 255";
export const DR_EPSILON = "#763ffb";
export const DR_EPSILON_RGB = "118, 63, 251";
export const DR_ZETA = "#b293fe";
export const DR_ZETA_RGB = "178, 147, 254";
export const DR_ETA = "#ff4d62";
export const DR_ETA_RGB = "255, 77, 98";
export const DR_THETA = "#ffc107";
export const DR_THETA_RGB = "255, 193, 7";
export const DR_IOTA = "#ff00cb";
export const DR_IOTA_RGB = "255, 0, 203";
export const DR_KAPPA = "#6af548";
export const DR_KAPPA_RGB = "106, 245, 72";
export const DR_LAMBDA = "#00cfff";
export const DR_LAMBDA_RGB = "0, 207, 255";
export const DR_MU = "#350c8cab";
export const DR_MU_RGB = "53, 12, 140, 0.67";
export const DR_NU = "transparent";
export const DR_NU_RGB = "0, 0, 0, 0";

/* stateful colors */
export const DR_SUCCESS = DR_KAPPA;
export const DR_SUCCESS_RGB = DR_KAPPA_RGB;
export const DR_INFO = DR_LAMBDA;
export const DR_INFO_RGB = DR_LAMBDA_RGB;
export const DR_WARNING = DR_THETA;
export const DR_WARNING_RGB = DR_THETA_RGB;
export const DR_DANGER = "#ff4d62";
export const DR_DANGER_RGB = DR_ETA_RGB;
